minimumReleaseAge: 4320
minimumReleaseAgeStrict: true
blockExoticSubdeps: true
trustPolicy: no-downgrade
verifyDepsBeforeRun: error

trustPolicyExclude:
  - undici-types@6.21.0

allowBuilds:
  '@google/genai': false
  esbuild: true
  protobufjs: false
